// These data are compiled by JakubPetriska (from GitHub JakubPetriska/quotes.csv)








var quoteDict = [
["Thomas Edison","Genius is one percent inspiration and ninety-nine percent perspiration."],
["Yogi Berra","You can observe a lot by watching."],
["Abraham Lincoln","A house divided against itself cannot stand."],
["Johann Wolfgang von Goethe","Difficulties increase the nearer we get to the goal."],
["Byron Pulsifer","Fate is in your hands and no one elses."],
["Lao Tzu","Be the chief but never the lord."],
["Carl Sandburg","Nothing happens unless first we dream."],
["Aristotle","Well begun is half done."],
["Yogi Berra","Life is a learning experience, only if you learn."],
["Margaret Sangster","Self-complacency is fatal to progress."],
["Buddha","Peace comes from within. Do not seek it without."],
["Byron Pulsifer","What you give is what you get."],
["Iris Murdoch","We can only learn to love by loving."],
["Karen Clark","Life is change. Growth is optional. Choose wisely."],
["Wayne Dyer","You'll see it when you believe it."],
["","Today is the tomorrow we worried about yesterday."],
["","It's easier to see the mistakes on someone else's paper."],
["","Every man dies. Not every man really lives."],
["Lao Tzu","To lead people walk behind them."],
["William Shakespeare","Having nothing, nothing can he lose."],
["Henry J. Kaiser","Trouble is only opportunity in work clothes."],
["Publilius Syrus","A rolling stone gathers no moss."],
["Napoleon Hill","Ideas are the beginning points of all fortunes."],
["Donald Trump","Everything in life is luck."],
["Lao Tzu","Doing nothing is better than being busy doing nothing."],
["Benjamin Spock","Trust yourself. You know more than you think you do."],
["Confucius","Study the past, if you would divine the future."],
["","The day is already blessed, find peace within it."],
["Sigmund Freud","From error to error one discovers the entire truth."],
["Benjamin Franklin","Well done is better than well said."],
["Ella Williams","Bite off more than you can chew, then chew it."],
["Buddha","Work out your own salvation. Do not depend on others."],
["Benjamin Franklin","One today is worth two tomorrows."],
["Christopher Reeve","Once you choose hope, anything's possible."],
["Albert Einstein","God always takes the simplest way."],
["Charles Kettering","One fails forward toward success."],
["","From small beginnings come great things."],
["Chinese proverb","Learning is a treasure that will follow its owner everywhere"],
["Socrates","Be as you wish to seem."],
["V. Naipaul","The world is always in movement."],
["John Wooden","Never mistake activity for achievement."],
["Haddon Robinson","What worries you masters you."],
["Pearl Buck","One faces the future with one's past."],
["Brian Tracy","Goals are the fuel in the furnace of achievement."],
["Leonardo da Vinci","Who sows virtue reaps honour."],
["Dalai Lama","Be kind whenever possible. It is always possible."],
["Chinese proverb","Talk doesn't cook rice."],
["Buddha","He is able who thinks he is able."],
["Larry Elder","A goal without a plan is just a wish."],
["Michael Korda","In order to succeed, we must first believe that we can."],
["Albert Einstein","Learn from yesterday, live for today, hope for tomorrow."],
["James Lowell","A weed is no more than a flower in disguise, Which is seen through at once, if love give a man eyes."],
["Yoda","Do, or do not. There is no try."],
["Harriet Beecher Stowe","All serious daring starts from within."],
["Byron Pulsifer","The best teacher is experience learned from failures."],
["Murray Gell-Mann","Think how hard physics would be if particles could think."],
["John Lennon","Love is the flower you've got to let grow."],
["Napoleon Hill","Don't wait. The time will never be just right."],
["Pericles","Time is the wisest counsellor of all."],
["Napoleon Hill","You give before you get."],
["Socrates","Wisdom begins in wonder."],
["Baltasar Gracian","Without courage, wisdom bears no fruit."],
["Aristotle","Change in all things is sweet."],
["Byron Pulsifer","What you fear is that which requires action to overcome."],
["Cullen Hightower","When performance exceeds ambition, the overlap is called success."],
["African proverb","When deeds speak, words are nothing."],
["Wayne Dyer","Real magic in relationships means an absence of judgement of others."],
["Albert Einstein","I never think of the future. It comes soon enough."],
["Ralph Emerson","Skill to do comes of doing."],
["Sophocles","Wisdom is the supreme part of happiness."],
["Maya Angelou","I believe that every person is born with talent."],
["Abraham Lincoln","Important principles may, and must, be inflexible."],
["Richard Evans","The undertaking of a new action brings new strength."],
["Ralph Emerson","The years teach much which the days never know."],
["Ralph Emerson","Our distrust is very expensive."],
["Bodhidharma","All know the way; few actually walk it."],
["Johann Wolfgang von Goethe","Great talent finds happiness in execution."],
["Michelangelo","Faith in oneself is the best and safest course."],
["Winston Churchill","Courage is going from failure to failure without losing enthusiasm."],
["Leo Tolstoy","The two most powerful warriors are patience and time."],
["Lao Tzu","Anticipate the difficult by managing the easy."],
["Buddha","Those who are free of resentful thoughts surely find peace."],
["Sophocles","A short saying often contains much wisdom."],
["","It takes both sunshine and rain to make a rainbow."],
["","A beautiful thing is never perfect."],
["Princess Diana","Only do what your heart tells you."],
["John Pierrakos","Life is movement-we breathe, we eat, we walk, we move!"],
["Eleanor Roosevelt","No one can make you feel inferior without your consent."],
["Richard Bach","Argue for your limitations, and sure enough, they're yours."],
["Seneca","Luck is what happens when preparation meets opportunity."],
["Napoleon Bonaparte","Victory belongs to the most persevering."],
["William Shakespeare","Love all, trust a few, do wrong to none."],
["Richard Bach","In order to win, you must expect to win."],
["Napoleon Hill","A goal is a dream with a deadline."],
["Napoleon Hill","You can do it if you believe you can."],
["Bo Jackson","Set your goals high, and don't stop till you get there."],
["","Every new day is another chance to change your life."],
["Thich Nhat Hanh","Smile, breathe, and go slowly."],
["Liberace","Nobody will believe in you unless you believe in yourself."],
["William Arthur Ward","Do more than dream: work."],
["Seneca","No man was ever wise by chance."],
["","Some pursue happiness, others create it."],
["William Shakespeare","He that is giddy thinks the world turns round."],
["Ellen Gilchrist","Don't ruin the present with the ruined past."],
["Albert Schweitzer","Do something wonderful, people may imitate it."],
["Neil Gaiman","We do what we do, because of who we are."],
["Eleanor Roosevelt","Do one thing every day that scares you."],
["Byron Pulsifer","If you cannot be silent be brilliant and thoughtful."],
["Carl Jung","Who looks outside, dreams; who looks inside, awakes."],
["Buddha","What we think, we become."],
["Lord Herbert","The shortest answer is doing the thing."],
["Leonardo da Vinci","All our knowledge has its origins in our perceptions."],
["","The harder you fall, the higher you bounce."],
["Anne Wilson Schaef","Trusting our intuition often saves us from disaster."],
["Sojourner Truth","Truth is powerful and it prevails."],
["Elizabeth Browning","Light tomorrow with today!"],
["German proverb","Silence is a fence around wisdom."],
["Madame de Stael","Society develops wit, but its contemplation alone forms genius."],
["Richard Bach","The simplest things are often the truest."],
["","Everyone smiles in the same language."],
["Bernadette Devlin","Yesterday I dared to struggle. Today I dare to win."],
["Napoleon Hill","No alibi will save you from accepting the responsibility."],
["Walt Disney","If you can dream it, you can do it."],
["Buddha","It is better to travel well than to arrive."],
["Anais Nin","Life shrinks or expands in proportion to one's courage."],
["Sun Tzu","You have to believe in yourself."],
["Wayne Dyer","Our intention creates our reality."],
["Confucius","Silence is a true friend who never betrays."],
["Johann Wolfgang von Goethe","Character develops itself in the stream of life."],
["American proverb","From little acorns mighty oaks do grow."],
["Jon Kabat-Zinn","You can't stop the waves, but you can learn to surf."],
["Gustave Flaubert","Reality does not conform to the ideal, but confirms it."],
["William Shakespeare","Speak low, if you speak love."],
["Johann Wolfgang von Goethe","A really great talent finds its happiness in execution."],
["John Lennon","Reality leaves a lot to the imagination."],
["Seneca","The greatest remedy for anger is delay."],
["Pearl Buck","Growth itself contains the germ of happiness."],
["","You can do what's reasonable or you can decide what's possible."],
["Leonardo da Vinci","Nothing strengthens authority so much as silence."],
["Confucius","Wherever you go, go with all your heart."],
["Albert Einstein","The only real valuable thing is intuition."],
["Ralph Emerson","Good luck is another name for tenacity of purpose."],
["Sylvia Voirol","Rainbows apologize for angry skies."],
["","Friendship isn't a big thing. It's a million little things."],
["Theophrastus","Time is the most valuable thing a man can spend."],
["Tony Robbins","Whatever happens, take responsibility."],
["Oscar Wilde","Experience is simply the name we give our mistakes."],
["Wayne Dyer","I think and that is all that I am."],
["","A good plan today is better than a perfect plan tomorrow."],
["Gloria Steinem","If the shoe doesn't fit, must we change the foot?"],
["Marcus Aurelius","Each day provides its own gifts."],
["Publilius Syrus","While we stop to think, we often miss our opportunity."],
["Bernard Shaw","Life is not about finding yourself. Life is about creating yourself."],
["Richard Bach","To bring anything into your life, imagine that it's already there."],
["German proverb","Begin to weave and God will give you the thread."],
["Confucius","The more you know yourself, the more you forgive yourself."],
["","Someone remembers, someone cares; your name is whispered in someone's prayers."],
["Mary Bethune","Without faith, nothing is possible. With it, nothing is impossible."],
["Albert Einstein","Once we accept our limits, we go beyond them."],
["","Don't be pushed by your problems; be led by your dreams."],
["Brian Tracy","Whatever we expect with confidence becomes our own self-fulfilling prophecy."],
["Pablo Picasso","Everything you can imagine is real."],
["Usman Asif","Fear is a darkroom where negatives develop."],
["Napoleon Bonaparte","The truest wisdom is a resolute determination."],
["Victor Hugo","Life is the flower for which love is the honey."],
["Epictetus","Freedom is the right to live as we wish."],
["","Change your thoughts, change your life!"],
["Robert Heller","Never ignore a gut feeling, but never believe that it's enough."],
["Marcus Aurelius","Loss is nothing else but change, and change is Nature's delight."],
["Byron Pulsifer","Someone is special only if you tell them."],
["","Today is the tomorrow you worried about yesterday."],
["Thich Nhat Hanh","There is no way to happiness, happiness is the way."],
["","The day always looks brighter from behind a smile."],
["","A stumble may prevent a fall."],
["Lao Tzu","He who talks more is sooner exhausted."],
["Lao Tzu","He who is contented is rich."],
["Plutarch","What we achieve inwardly will change outer reality."],
["Ralph Waldo Emerson","Our strength grows out of our weaknesses."],
["Mahatma Gandhi","We must become the change we want to see."],
["Napoleon Hill","Happiness is found in doing, not merely possessing."],
["","Put your future in good hands - your own."],
["Wit","We choose our destiny in the way we treat others."],
["Voltaire","No snowflake in an avalanche ever feels responsible."],
["Virgil","Fortune favours the brave."],
["Joseph Stalin","I believe in one thing only, the power of human will."],
["Robert Frost","The best way out is always through."],
["Seneca","The mind unlearns with difficulty what it has long learned."],
["Abraham Lincoln","I destroy my enemies when I make them my friends."],
["Thomas Fuller","No garden is without its weeds."],
["Elbert Hubbard","There is no failure except in no longer trying."],
["Turkish proverb","Kind words will unlock an iron door."],
["Hugh Miller","Problems are only opportunities with thorns on them."],
["A. Powell Davies","Life is just a chance to grow a soul."],
["Johann Wolfgang von Goethe","Mountains cannot be surmounted except by winding paths."],
["Thich Nhat Hanh","May our hearts garden of awakening bloom with hundreds of flowers."],
["John Dryden","Fortune befriends the bold."],
["Friedrich von Schiller","Keep true to the dreams of thy youth."],
["Mike Ditka","You're never a loser until you quit trying."],
["Immanuel Kant","Science is organized knowledge. Wisdom is organized life."],
["Johann Wolfgang von Goethe","Knowing is not enough; we must apply!"],
["Richard Bach","Strong beliefs win strong men, and then make them stronger."],
["Albert Camus","Autumn is a second spring when every leaf is a flower."],
["Toni Morrison","If you surrender to the wind, you can ride it."],
["Helen Keller","Keep yourself to the sunshine and you cannot see the shadow."],
["Paulo Coelho","Write your plans in pencil and give God the eraser."],
["Pablo Picasso","Inspiration exists, but it has to find you working."],
["Jonathan Kozol","Pick battles big enough to matter, small enough to win."],
["Janis Joplin","Don't compromise yourself. You are all you've got."],
["Sophocles","A short saying often contains much wisdom."],
["Epictetus","Difficulties are things that show a person what they are."],
["Honore de Balzac","When you doubt your power, you give power to your doubt."],
["Ovid","The cause is hidden. The effect is visible to all."],
["Francis Bacon","A prudent question is one half of wisdom."],
["Tony Robbins","The path to success is to take massive, determined action."],
["Manuel Puig","I allow my intuition to lead my path."],
["William R. Inge","Nature takes away any faculty that is not used."],
["Epictetus","If you wish to be a writer, write."],
["Wayne Dyer","There is no way to prosperity, prosperity is the way."],
["Jim Rohn","Either you run the day or the day runs you."],
["Publilius Syrus","Better be ignorant of a matter than half know it."],
["Oprah Winfrey","Follow your instincts. That is where true wisdom manifests itself."],
["Benjamin Franklin","There never was a good knife made of bad steel."],
["Anatole France","To accomplish great things, we must dream as well as act."],
["Saint Augustine","Patience is the companion of wisdom."],
["Buddha","The mind is everything. What you think you become."],
["Voltaire","To enjoy life, we must touch much of it lightly."],
["Maya Lin","To fly, we have to have resistance."],
["","What you see depends on what you're looking for."],
["Blaise Pascal","The heart has its reasons which reason knows not of."],
["William Shakespeare","Be great in act, as you have been in thought."],
["Napoleon Bonaparte","Imagination rules the world."],
["Blaise Pascal","Kind words do not cost much. Yet they accomplish much."],
["Michelangelo","There is no greater harm than that of time wasted."],
["Jonas Salk","Intuition will tell the thinking mind where to look next."],
["","Worry gives a small thing a big shadow."],
["Napoleon Hill","Fears are nothing more than a state of mind."],
["Lao Tzu","A journey of a thousand miles begins with one step."],
["Peter Drucker","Efficiency is doing things right; effectiveness is doing the right things."],
["Luisa Sigea","Blaze with the fire that is never extinguished."],
["Dr. Seuss","Don't cry because it's over. Smile because it happened."],
["Jason Fried","No is easier to do. Yes is easier to say."],
["Confucius","To be wrong is nothing unless you continue to remember it."],
["Babe Ruth","Yesterday's home runs don't win today's games."],
["Carlyle","Silence is deep as Eternity, Speech is shallow as Time."],
["Leo F. Buscaglia","Don't smother each other. No one can grow in the shade."],
["Lao Tzu","An ant on the move does more than a dozing ox."],
["Indira Gandhi","You can't shake hands with a clenched fist."],
["Plato","A good decision is based on knowledge and not on numbers."],
["Confucius","The cautious seldom err."],
["Frederick Douglass","If there is no struggle, there is no progress."],
["Willa Cather","Where there is great love, there are always miracles."],
["John Lennon","Time you enjoy wasting, is not wasted time."],
["Richard Bach","Every problem has a gift for you in its hands."],
["Jean de la Fontaine","Sadness flies away on the wings of time."],
["Publilius Syrus","I have often regretted my speech, never my silence."],
["Thomas Jefferson","Never put off till tomorrow what you can do today."],
["Thomas Dewar","Minds are like parachutes. They only function when open."],
["George Patton","If a man does his best, what else is there?"],
["Benjamin Disraeli","The secret of success is constancy to purpose."],
["Ralph Emerson","Life is a progress, and not a station."],
["Horace Friess","All seasons are beautiful for the person who carries happiness within."],
["Elbert Hubbard","To avoid criticism, do nothing, say nothing, be nothing."],
["Ovid","All things change; nothing perishes."],
["Haynes Bayly","Absence makes the heart grow fonder."],
["Lauren Bacall","Imagination is the highest kite one can fly."],
["Frank Herbert","The beginning of knowledge is the discovery of something we do not understand."],
["Elizabeth Browning","Love doesn't make the world go round, love is what makes the ride worthwhile."],
["Arthur Conan Doyle","Whenever you have eliminated the impossible, whatever remains, however improbable, must be the truth."],
["J. Willard Marriott","Good timber does not grow with ease; the stronger wind, the stronger trees."],
["Dalai Lama","I believe that we are fundamentally the same and have the same basic potential."],
["Edward Gibbon","The winds and waves are always on the side of the ablest navigators."],
["Eleanor Roosevelt","The future belongs to those who believe in the beauty of their dreams."],
["","To get something you never had, you have to do something you never did."],
["","Be thankful when you don't know something for it gives you the opportunity to learn."],
["Mahatma Gandhi","Strength does not come from physical capacity. It comes from an indomitable will."],
["Og Mandino","Each misfortune you encounter will carry in it the seed of tomorrow's good luck."],
["Lewis B. Smedes","To forgive is to set a prisoner free and realize that prisoner was you."],
["Buddha","In separateness lies the world's greatest misery, in compassion lies the world's true strength."],
["Nikos Kazantzakis","By believing passionately in something that does not yet exist, we create it."],
["","Letting go isn't the end of the world; it's the beginning of a new life."],
["John Eliot","All the great performers I have worked with are fuelled by a personal dream."],
["A. A. Milne","One of the advantages of being disorderly is that one is constantly making exciting discoveries."],
["Marie Curie","I never see what has been done; I only see what remains to be done."],
["Seneca","Begin at once to live and count each separate day as a separate life."],
["Lawrence Peter","If you don't know where you are going, you will probably end up somewhere else."],
["Hannah More","It is not so important to know everything as to appreciate what we learn."],
["John Berry","The bird of paradise alights only upon the hand that does not grasp."],
["William Yeats","Think as a wise man but communicate in the language of the people."],
["Epictetus","Practice yourself, for heaven's sake in little things, and then proceed to greater."],
["Seneca","If one does not know to which port one is sailing, no wind is favorable."],
["","Our greatest glory is not in never falling but in rising everytime we fall."],
["","Being right is highly overrated. Even a stopped clock is right twice a day."],
["Ken S. Keyes","To be upset over what you don't have is to waste what you do have."],
["Thomas Edison","If we all did the things we are capable of doing, we would literally astound ourselves."],
["Marie Curie","Nothing in life is to be feared. It is only to be understood."],
["Tony Robbins","Successful people ask better questions, and as a result, they get better answers."],
["","Love is not blind; it simply enables one to see things others fail to see."],
["Anne Schaef","Life is a process. We are a process. The universe is a process."],
["Eleanor Roosevelt","I think somehow we learn who we really are and then live with that decision."],
["Kenneth Patton","We learn what we have said from those who listen to our speaking."],
["Kahlil Gibran","A little knowledge that acts is worth infinitely more than much knowledge that is idle."],
["","If you get up one more time than you fall, you will make it through."],
["Flora Whittemore","The doors we open and close each day decide the lives we live."],
["H. W. Arnold","The worst bankrupt in the world is the person who has lost his enthusiasm."],
["Buddha","Happiness comes when your work and words are of benefit to yourself and others."],
["","Don't focus on making the right decision, focus on making the decision the right one."],
["Wayne Dyer","Everything is perfect in the universe, even your desire to improve it."],
["Eden Phillpotts","The universe is full of magical things, patiently waiting for our wits to grow sharper."],
["Buddha","Just as a candle cannot burn without fire, men cannot live without a spiritual life."],
["Mark Twain","A thing long expected takes the form of the unexpected when at last it comes."],
["Benjamin Disraeli","Action may not always bring happiness; but there is no happiness without action."],
["Oprah Winfrey","I don't believe in failure. It is not failure if you enjoyed the process."],
["Confucius","What you do not want done to yourself, do not do to others."],
["Winston Churchill","Short words are best and the old words when short are best of all."],
["Buddha","If you light a lamp for somebody, it will also brighten your path."],
["Lin-yutang","I have done my best: that is about all the philosophy of living one needs."],
["Benjamin Disraeli","Through perseverance many people win success out of what seemed destined to be certain failure."],
["Byron Pulsifer","Give thanks for the rain of life that propels us to reach new horizons."],
["","Love is just a word until someone comes along and gives it meaning."],
["","We all have problems. The way we solve them is what makes us different."],
["Dave Weinbaum","The secret to a rich life is to have more beginnings than endings."],
["Ralph Waldo Emerson","It is only when the mind and character slumber that the dress can be seen."],
["Maya Angelou","If you don't like something, change it. If you can't change it, change your attitude."],
["Confucius","Reviewing what you have learned and learning anew, you are fit to be a teacher."],
["Augustinus Sanctus","The world is a book, and those who do not travel read only a page."],
["Henri-Frederic Amiel","So long as a person is capable of self-renewal they are a living being."],
["Louisa Alcott","I'm not afraid of storms, for I'm learning how to sail my ship."],
["Voltaire","Think for yourselves and let others enjoy the privilege to do so too."],
["Annie Dillard","How we spend our days is, of course, how we spend our lives."],
["Man Ray","It has never been my object to record my dreams, just to realize them."],
["Sigmund Freud","The most complicated achievements of thought are possible without the assistance of consciousness."],
["Wayne Dyer","Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice."],
["Napoleon Hill","Most great people have attained their greatest success just one step beyond their greatest failure."],
["Henry Ford","If you think you can, you can. And if you think you can't, you're right."],
["St. Augustine","Better to have loved and lost, than to have never loved at all."],
["Leo Tolstoy","Everyone thinks of changing the world, but no one thinks of changing himself."],
["Richard Bach","The best way to pay for a lovely moment is to enjoy it."],
["Winston Churchill","You have enemies? Good. That means you've stood up for something, sometime in your life."],
["John De Paola","Slow down and everything you are chasing will come around and catch you."],
["Buddha","Your worst enemy cannot harm you as much as your own unguarded thoughts."],
["Lily Tomlin","I always wanted to be somebody, but I should have been more specific."],
["John Lennon","Yeah we all shine on, like the moon, and the stars, and the sun."],
["Martin Fischer","Knowledge is a process of piling up facts; wisdom lies in their simplification."],
["Albert Einstein","Life is like riding a bicycle. To keep your balance you must keep moving."],
["Albert Schweitzer","We should all be thankful for those people who rekindle the inner spirit."],
["Thomas Edison","Opportunity is missed by most because it is dressed in overalls and looks like work."],
["Albert Einstein","Feeling and longing are the motive forces behind all human endeavor and human creations."],
["Johann Wolfgang von Goethe","In the end we retain from our studies only that which we practically apply."],
["Lao Tzu","If you correct your mind, the rest of your life will fall into place."],
["Ralph Emerson","The world makes way for the man who knows where he is going."],
["Napoleon Hill","When your desires are strong enough, you will appear to possess superhuman powers to achieve."],
["John Adams","Patience and perseverance have a magical effect before which difficulties disappear and obstacles vanish."],
["Henry David Thoreau","I cannot make my days longer so I strive to make them better."],
["Chinese proverb","Tension is who you think you should be. Relaxation is who you are."],
["Helen Keller","Never bend your head. Always hold it high. Look the world straight in the eye."],
["Albert Schweitzer","One who gains strength by overcoming obstacles possesses the only strength which can overcome adversity."],
["Calvin Coolidge","We cannot do everything at once, but we can do something at once."],
["Abraham Lincoln","You have to do your own growing no matter how tall your grandfather was."],
["","Invent your world. Surround yourself with people, color, sounds, and work that nourish you."],
["General Douglas MacArthur","It is fatal to enter any war without the will to win it."],
["Julius Charles Hare","Be what you are. This is the first step toward becoming better than you are."],
["Buckminster Fuller","There is nothing in a caterpillar that tells you it's going to be a butterfly."],
["Dalai Lama","Love and compassion open our own inner life, reducing stress, distrust and loneliness."],
["Walter Lippmann","Ideals are an imaginative understanding of that which is desirable in that which is possible."],
["Confucius","The superior man is satisfied and composed; the mean man is always full of distress."],
["Bruce Lee","If you spend too much time thinking about a thing, you'll never get it done."],
["Buddha","The way is not in the sky. The way is in the heart."],
["Abraham Lincoln","Most people are about as happy as they make up their minds to be."],
["Buddha","Three things cannot be long hidden: the sun, the moon, and the truth."],
["Dalai Lama","More often than not, anger is actually an indication of weakness rather than of strength."],
["Jim Beggs","Before you put on a frown, make absolutely sure there are no smiles available."],
["Donald Kircher","A man of ability and the desire to accomplish something can do anything."],
["Buddha","You, yourself, as much as anybody in the entire universe, deserve your love and affection."],
["Eckhart Tolle","It is not uncommon for people to spend their whole life waiting to start living."],
["H. Jackson Browne","Don't be afraid to go out on a limb. That's where the fruit is."],
["Marquis Vauvenargues","Wicked people are always surprised to find ability in those that are good."],
["Charlotte Bronte","Life is so constructed that an event does not, cannot, will not, match the expectation."],
["Wayne Dyer","If you change the way you look at things, the things you look at change."],
["Napoleon Hill","No man can succeed in a line of endeavor which he does not like."],
["Buddha","You will not be punished for your anger, you will be punished by your anger."],
["Robert Stevenson","Don't judge each day by the harvest you reap but by the seeds you plant."],
["Andy Warhol","They always say that time changes things, but you actually have to change them yourself."],
["Benjamin Disraeli","Never apologize for showing feelings. When you do so, you apologize for the truth."],
["Pema Chodron","The truth you believe and cling to makes you unavailable to hear anything new."],
["Horace","Adversity has the effect of eliciting talents, which in prosperous circumstances would have lain dormant."],
["Morris West","If you spend your whole life waiting for the storm, you'll never enjoy the sunshine."],
["Franklin Roosevelt","The only limit to our realization of tomorrow will be our doubts of today."],
["Edwin Chapin","Every action of our lives touches on some chord that will vibrate in eternity."],
["Les Brown","Shoot for the moon. Even if you miss, you'll land among the stars."],
["Confucius","It does not matter how slowly you go as long as you do not stop."],
["","Every day may not be good, but there's something good in every day."],
["Abraham Lincoln","Most folks are about as happy as they make up their minds to be."],
["Lao Tzu","If you would take, you must first give, this is the beginning of intelligence."],
["","Some people think it's holding that makes one strong, sometimes it's letting go."],
["Havelock Ellis","It is on our failures that we base a new and different and better success."],
["John Ruskin","Quality is never an accident; it is always the result of intelligent effort."],
["Confucius","To study and not think is a waste. To think and not study is dangerous."],
["Ralph Emerson","Life is a succession of lessons, which must be lived to be understood."],
["Thomas Hardy","Time changes everything except something within us which is always surprised by change."],
["Wayne Dyer","You are important enough to ask and you are blessed enough to receive back."],
["Napoleon Hill","If you cannot do great things, do small things in a great way."],
["Oprah Winfrey","If you want your life to be more rewarding, you have to change the way you think."],
["Byron Pulsifer","Transformation doesn't take place with a vacuum; instead, it occurs when we are indirectly and directly connected to all those around us."],
["Leonardo Ruiz","The only difference between your abilities and others is the ability to put yourself in their shoes and actually try."],
["Leon Blum","The free man is he who does not fear to go to the end of his thought."],
["Ralph Emerson","Great are they who see that spiritual is stronger than any material force, that thoughts rule the world."],
["Bernard Shaw","A life spent making mistakes is not only more honourable but more useful than a life spent doing nothing."],
["Lao Tzu","The wise man does not lay up his own treasures. The more he gives to others, the more he has for his own."],
["Charles Dickens","Don't leave a stone unturned. It's always something, to know you have done the most you could."],
["Dalai Lama","By going beyond your own problems and taking care of others, you gain inner strength, self-confidence, courage, and a greater sense of calm."],
["Sam Keen","We come to love not by finding a perfect person, but by learning to see an imperfect person perfectly."],
["Walt Emerson","What lies behind us and what lies before us are tiny matters compared to what lies within us."],
["John Astin","There are things so deep and complex that only intuition can reach it in our stage of development as human beings."],
["Elbert Hubbard","A little more persistence, a little more effort, and what seemed hopeless failure may turn to glorious success."],
["Henry Moore","There is no retirement for an artist, it's your way of living so there is no end to it."],
["Confucius","I will not be concerned at other men's not knowing me; I will be concerned at my own want of ability."],
["","Why worry about things you can't control when you can keep yourself busy controlling the things that depend on you?"],
["Laozi","When you are content to be simply yourself and don't compare or compete, everybody will respect you."],
["William Shakespeare","Be not afraid of greatness: some are born great, some achieve greatness, and some have greatness thrust upon them."],
["George Sheehan","Success means having the courage, the determination, and the will to become the person you believe you were meant to be."],
["Thomas Jefferson","Do you want to know who you are? Don't ask. Act! Action will delineate and define you."],
["Antoine de Saint-Exupery","It is only with the heart that one can see rightly, what is essential is invisible to the eye."],
["Marcel Proust","Let us be grateful to people who make us happy; they are the charming gardeners who make our souls blossom."],
["Epictetus","Make the best use of what is in your power, and take the rest as it happens."],
["Louise Hay","The thoughts we choose to think are the tools we use to paint the canvas of our lives."],
["W. Clement Stone","No matter how carefully you plan your goals they will never be more that pipe dreams unless you pursue them with gusto."],
["Robert McKain","The reason most goals are not achieved is that we spend our time doing second things first."],
["John Quincy Adams","If your actions inspire others to dream more, learn more, do more and become more, you are a leader."],
["Thomas Jefferson","I'm a great believer in luck, and I find the harder I work, the more I have of it."],
["Ralph Emerson","Do not waste yourself in rejection, nor bark against the bad, but chant the beauty of the good."],
["Johann Wolfgang von Goethe","The person born with a talent they are meant to use will find their greatest happiness in using it."],
["William Saroyan","Good people are good because they've come to wisdom through failure. We get very little wisdom from success, you know."],
["Byron Pulsifer","Your destiny isn't just fate; it is how you use your own developed abilities to get what you want."],
["Leonardo da Vinci","Iron rusts from disuse; water loses its purity from stagnation... even so does inaction sap the vigour of the mind."],
["Isaac Asimov","A subtle thought that is in error may yet give rise to fruitful inquiry that can establish truths of great value."],
["Henry Van Dyke","Be glad of life because it gives you the chance to love, to work, to play, and to look up at the stars."],
["Yogi Berra","You got to be careful if you don't know where you're going, because you might not get there."],
["Naguib Mahfouz","You can tell whether a man is clever by his answers. You can tell whether a man is wise by his questions."],
["Anthony Robbins","Life is a gift, and it offers us the privilege, opportunity, and responsibility to give something back by becoming more."],
["John Wooden","You can't let praise or criticism get to you. It's a weakness to get caught up in either one."],
["Og Mandino","I will love the light for it shows me the way, yet I will endure the darkness because it shows me the stars."],
["Jane Addams","Our doubts are traitors and make us lose the good we often might win, by fearing to attempt."],
["Thomas Carlyle","By nature man hates change; seldom will he quit his old home till it has actually fallen around his ears."],
["M. Scott Peck","Until you value yourself, you won't value your time. Until you value your time, you won't do anything with it."],
["Maureen Dowd","The minute you settle for less than you deserve, you get even less than you settled for."],
["Charles Darwin","The highest stage in moral ure at which we can arrive is when we recognize that we ought to control our thoughts."],
["","It is better to take many small steps in the right direction than to make a great leap forward only to stumble backward."],
["Dalai Lama","If we have a positive mental attitude, then even when surrounded by hostility, we shall not lack inner peace."],
["Christopher Morley","There is only one success - to be able to spend your life in your own way."],
["Hannah Arendt","Promises are the uniquely human way of ordering the future, making it predictable and reliable to the extent that this is humanly possible."],
["Alan Cohen","Appreciation is the highest form of prayer, for it acknowledges the presence of good wherever you shine the light of your thankful thoughts."],
["Aldous Huxley","There is only one corner of the universe you can be certain of improving, and that's your own self."],
["Marian Edelman","You're not obligated to win. You're obligated to keep trying to do the best you can every day."],
["Byron Pulsifer","Everyone can taste success when the going is easy, but few know how to taste victory when times get tough."],
["Sue Patton Thoele","Deep listening is miraculous for both listener and speaker. When someone receives us with open-hearted, non-judging, intensely interested listening, our spirits expand."],
["Frank Crane","You may be deceived if you trust too much, but you will live in torment if you don't trust enough."],
["Lao Tzu","Great indeed is the sublimity of the Creative, to which all beings owe their beginning and which permeates all heaven."],
["Kathleen Norris","All that is necessary is to accept the impossible, do without the indispensable, and bear the intolerable."],
["Confucius","Choose a job you love, and you will never have to work a day in your life."],
["Eckhart Tolle","You cannot find yourself by going into the past. You can find yourself by coming into the present."],
["Anne Bronte","All our talents increase in the using, and the every faculty, both good and bad, strengthen by exercise."],
["Richard Bach","In order to live free and happily, you must sacrifice boredom. It is not always an easy sacrifice."],
["Desiderius Erasmus","The fox has many tricks. The hedgehog has but one. But that is the best of all."],
["Arthur Rubinstein","Of course there is no formula for success, except perhaps an unconditional acceptance of life, and what it brings."],
["Louis Pasteur","Let me tell you the secret that has led me to my goal: my strength lies solely in my tenacity"],
["Rumi","Something opens our wings. Something makes boredom and hurt disappear. Someone fills the cup in front of us: We taste only sacredness."],
["Sogyal Rinpoche","We must never forget that it is through our actions, words, and thoughts that we have a choice."],
["Dennis Kimbro","We see things not as they are, but as we are. Our perception is shaped by our previous experiences."],
["William Penn","True silence is the rest of the mind; it is to the spirit what sleep is to the body, nourishment and refreshment."],
["Immanuel Kant","All our knowledge begins with the senses, proceeds then to the understanding, and ends with reason. There is nothing higher than reason."],
["Buddha","The thought manifests as the word. The word manifests as the deed. The deed develops into habit. And the habit hardens into character."],
["","As the rest of the world is walking out the door, your best friends are the ones walking in."],
["Byron Pulsifer","Patience is a virtue but you will never ever accomplish anything if you don't exercise action over patience."],
["Robert Lynd","Any of us can achieve virtue, if by virtue we merely mean the avoidance of the vices that do not attract us."],
["Ralph Emerson","If the single man plant himself indomitably on his instincts, and there abide, the huge world will come round to him."],
["Donald Trump","Money was never a big motivation for me, except as a way to keep score. The real excitement is playing the game."],
["Eleanor Roosevelt","Friendship with oneself is all important because without it one cannot be friends with anybody else in the world."],
["Robert Fulghum","Peace is not something you wish for. It's something you make, something you do, something you are, and something you give away."],
["Bruce Lee","A wise man can learn more from a foolish question than a fool can learn from a wise answer."],
["Arthur Schopenhauer","Every man takes the limits of his own field of vision for the limits of the world."],
["Andre Gide","One does not discover new lands without consenting to lose sight of the shore for a very long time."],
["Sai Baba","What is new in the world? Nothing. What is old in the world? Nothing. Everything has always been and will always be."],
["Dalai Lama","Genuine love should first be directed at oneself. if we do not love ourselves, how can we love others?"],
["Tom Lehrer","Life is like a sewer. What you get out of it depends on what you put into it."],
["Bruce Lee","Notice that the stiffest tree is most easily cracked, while the bamboo or willow survives by bending with the wind."],
["Alfred Sheinwold","Learn all you can from the mistakes of others. You won't have time to make them all yourself."],
["Sri Chinmoy","Judge nothing, you will be happy. Forgive everything, you will be happier. Love everything, you will be happiest."],
["Johann Wolfgang von Goethe","People are so constituted that everybody would rather undertake what they see others do, whether they have an aptitude for it or not."],
["James Freeman Clarke","We are either progressing or retrograding all the while. There is no such thing as remaining stationary in this life."],
["Anais Nin","The possession of knowledge does not kill the sense of wonder and mystery. There is always more mystery."],
["Marcus Aurelius","Everything that happens happens as it should, and if you observe carefully, you will find this to be so."],
["Wayne Dyer","What we think determines what happens to us, so if we want to change our lives, we need to stretch our minds."],
["Buddha","In a controversy the instant we feel anger we have already ceased striving for the truth, and have begun striving for ourselves."],
["Sydney Smith","It is the greatest of all mistakes to do nothing because you can only do little - do what you can."],
["Confucius","When you see a man of worth, think of how you may emulate him. When you see one who is unworthy, examine yourself."],
["Mary Kay Ash","Aerodynamically, the bumblebee shouldn't be able to fly, but the bumblebee doesn't know that so it goes on flying anyway."],
["Lloyd Jones","Those who try to do something and fail are infinitely better than those who try nothing and succeed."],
["Vista Kelly","Snowflakes are one of nature's most fragile things, but just look what they can do when they stick together."],
["Ben Stein","The first step to getting the things you want out of life is this: decide what you want."],
["","Why compare yourself with others? No one in the entire world can do a better job of being you than you."],
["Aldous Huxley","Experience is not what happens to a man. It is what a man does with what happens to him."],
["","A good teacher is like a candle - it consumes itself to light the way for others."],
["Oscar Wilde","The only thing to do with good advice is to pass it on. It is never of any use to oneself."],
["","Life is not measured by the number of breaths we take, but by the moments that take our breath away."],
["Honore de Balzac","The smallest flower is a thought, a life answering to some feature of the Great Whole, of whom they have a persistent intuition."],
["Jacob Braude","Consider how hard it is to change yourself and you'll understand what little chance you have in trying to change others."],
["Vince Lombardi","If you'll not settle for anything less than your best, you will be amazed at what you can accomplish in your lives."],
["Oliver Holmes","What lies behind us and what lies before us are small matters compared to what lies within us."],
["Dalai Lama","With the realization of ones own potential and self-confidence in ones ability, one can build a better world."],
["Nelson Mandela","There is nothing like returning to a place that remains unchanged to find the ways in which you yourself have altered."],
["Robert Anthony","Forget about all the reasons why something may not work. You only need to find one good reason why it will."],
["Aristotle","It is the mark of an educated mind to be able to entertain a thought without accepting it."],
["Washington Irving","Love is never lost. If not reciprocated, it will flow back and soften and purify the heart."],
["Anne Frank","We all live with the objective of being happy; our lives are all different and yet the same."],
["Byron Pulsifer","Many people think of prosperity that concerns money only to forget that true prosperity is of the mind."],
["Thich Nhat Hanh","To be beautiful means to be yourself. You don't need to be accepted by others. You need to accept yourself."],
["Buddha","Do not overrate what you have received, nor envy others. He who envies others does not obtain peace of mind."],
["Jessamyn West","It is very easy to forgive others their mistakes; it takes more grit to forgive them for having witnessed your own."],
["Plato","Bodily exercise, when compulsory, does no harm to the body; but knowledge which is acquired under compulsion obtains no hold on the mind."],
["Bruce Lee","Always be yourself, express yourself, have faith in yourself, do not go out and look for a successful personality and duplicate it."],
["Charlotte Gilman","Let us revere, let us worship, but erect and open-eyed, the highest, not the lowest; the future, not the past!"],
["Mother Teresa","Every time you smile at someone, it is an action of love, a gift to that person, a beautiful thing."],
["Margaret Runbeck","Silences make the real conversations between friends. Not the saying but the never needing to say is what counts."],
["Dalai Lama","The key to transforming our hearts and minds is to have an understanding of how our thoughts and emotions work."],
["Johann Wolfgang von Goethe","If you must tell me your opinions, tell me what you believe in. I have plenty of douts of my own."],
["Ovid","Chance is always powerful. Let your hook be always cast; in the pool where you least expect it, there will be a fish."],
["Og Mandino","I seek constantly to improve my manners and graces, for they are the sugar to which all are attracted."],
["James Barrie","We never understand how little we need in this world until we know the loss of it."],
["","The real measure of your wealth is how much you'd be worth if you lost all your money."],
["Buddha","To keep the body in good health is a duty... otherwise we shall not be able to keep our mind strong and clear."],
["Bruce Lee","Take no thought of who is right or wrong or who is better than. Be not for or against."],
["Everett Dirksen","I am a man of fixed and unbending principles, the first of which is to be flexible at all times."],
["Byron Pulsifer","Today, give a stranger a smile without waiting for it may be the joy they need to have a great day."],
["Henry Miller","The moment one gives close attention to anything, even a blade of grass, it becomes a mysterious, awesome, indescribably magnificent world in itself."],
["Lao Tzu","At the center of your being you have the answer; you know who you are and you know what you want."],
["Niels Bohr","How wonderful that we have met with a paradox. Now we have some hope of making progress."],
["Georg Lichtenberg","Everyone is a genius at least once a year. A real genius has his original ideas closer together."],
["Anais Nin","Dreams pass into the reality of action. From the actions stems the dream again; and this interdependence produces the highest form of living."],
["Gloria Steinem","Without leaps of imagination, or dreaming, we lose the excitement of possibilities. Dreaming, after all, is a form of planning."],
["Byron Pulsifer","Sadness may be part of life but there is no need to let it dominate your entire life."],
["Charles Schwab","Keeping a little ahead of conditions is one of the secrets of business, the trailer seldom goes far."],
["Epictetus","Nature gave us one tongue and two ears so we could hear twice as much as we speak."],
["Barbara Baron","Don't wait for your feelings to change to take the action. Take the action and your feelings will change."],
["Richard Bach","You are always free to change your mind and choose a different future, or a different past."],
["Lou Holtz","You were not born a winner, and you were not born a loser. You are what you make yourself be."],
["Napoleon Hill","Cherish your visions and your dreams as they are the children of your soul, the blueprints of your ultimate achievements."],
["Napoleon Hill","Cherish your visions and your dreams as they are the children of your soul; the blueprints of your ultimate achievements."],
["Robert Stevenson","To be what we are, and to become what we are capable of becoming, is the only end of life."],
["Charles DeLint","The road leading to a goal does not separate you from the destination; it is essentially a part of it."],
["Bruce Lee","Take things as they are. Punch when you have to punch. Kick when you have to kick."],
["Albert Einstein","I believe that a simple and unassuming manner of life is best for everyone, best both for the body and the mind."],
["","Though no one can go back and make a brand new start, anyone can start from now and make a brand new ending."],
["Paavo Nurmi","Mind is everything: muscle, pieces of rubber. All that I am, I am because of my mind."],
["Anne Frank","How wonderful it is that nobody need wait a single moment before starting to improve the world."],
["","A friend is someone who understands your past, believes in your future, and accepts you just the way you are."],
["Ralph Emerson","It is one of the blessings of old friends that you can afford to be stupid with them."],
["Tryon Edwards","He that never changes his opinions, never corrects his mistakes, and will never be wiser on the morrow than he is today."],
["Abraham Lincoln","Give me six hours to chop down a tree and I will spend the first four sharpening the axe."],
["E. M. Forster","One must be fond of people and trust them if one is not to make a mess of life."],
["David Seamans","We cannot change our memories, but we can change their meaning and the power they have over us."],
["Confucius","Being in humaneness is good. If we select other goodness and thus are far apart from humaneness, how can we be the wise?"],
["Byron Pulsifer","To give hope to someone occurs when you teach them how to use the tools to do it for themselves."],
["Lucille Ball","I'd rather regret the things that I have done than the things that I have not done."],
["Eckhart Tolle","The past has no power to stop you from being present now. Only your grievance about the past can do that."],
["Ralph Emerson","If the stars should appear but one night every thousand years how man would marvel and adore."],
["Laurence J. Peter","There are two kinds of failures: those who thought and never did, and those who did and never thought."],
["Elizabeth Arden","I'm not interested in age. People who tell me their age are silly. You're as old as you feel."],
["Dalai Lama","I find hope in the darkest of days, and focus in the brightest. I do not judge the universe."],
["Confucius","When it is obvious that the goals cannot be reached, don't adjust the goals, adjust the action steps."],
["Nikola Tesla","Our virtues and our failings are inseparable, like force and matter. When they separate, man is no more."],
["Leo Aikman","Blessed is the person who is too busy to worry in the daytime, and too sleepy to worry at night."],
["Pablo Picasso","He can who thinks he can, and he can't who thinks he can't. This is an inexorable, indisputable law."],
["Vernon Cooper","These days people seek knowledge, not wisdom. Knowledge is of the past, wisdom is of the future."],
["Benjamin Disraeli","One secret of success in life is for a man to be ready for his opportunity when it comes."],
["Dalai Lama","People take different roads seeking fulfilment and happiness. Just because they're not on your road doesn't mean they've gotten lost."],
["Carl Jung","The shoe that fits one person pinches another; there is no recipe for living that suits all cases."],
["Buddha","There are only two mistakes one can make along the road to truth; not going all the way, and not starting."],
["Marcus Aurelius","Very little is needed to make a happy life; it is all within yourself, in your way of thinking."],
["","Giving up doesn't always mean you are weak. Sometimes it means that you are strong enough to let go."],
["Johann Wolfgang von Goethe","Treat people as if they were what they ought to be and you help them to become what they are capable of being."],
["Thich Nhat Hanh","The most precious gift we can offer anyone is our attention. When mindfulness embraces those we love, they will bloom like flowers."],
["Jack Dixon","If you focus on results, you will never change. If you focus on change, you will get results."],
["G. K. Chesterton","I would maintain that thanks are the highest form of thought, and that gratitude is happiness doubled by wonder."],
["Denis Waitley","There are two primary choices in life: to accept conditions as they exist, or accept the responsibility for changing them."],
["Lao-Tzu","All difficult things have their origin in that which is easy, and great things in that which is small."],
["Byron Pulsifer","You can be what you want to be. You have the power within and we will help you always."],
["Johannes Gaertner","To speak gratitude is courteous and pleasant, to enact gratitude is generous and noble, but to live gratitude is to touch Heaven."],
["Doug Larson","Wisdom is the reward you get for a lifetime of listening when you'd have preferred to talk."],
["Charles Lamb","The greatest pleasure I know is to do a good action by stealth, and to have it found out by accident."],
["John Muir","When one tugs at a single thing in nature, he finds it attached to the rest of the world."],
["Winston Churchill","Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen."],
["Helen Keller","The best and most beautiful things in the world cannot be seen or even touched. They must be felt with the heart."],
["Buddha","To live a pure unselfish life, one must count nothing as ones own in the midst of abundance."],
["Thomas Edison","Many of life's failures are people who did not realize how close they were to success when they gave up."],
["William Ward","When we seek to discover the best in others, we somehow bring out the best in ourselves."],
["Michael Jordan","If you accept the expectations of others, especially negative ones, then you never will change the outcome."],
["Oliver Holmes","A man may fulfil the object of his existence by asking a question he cannot answer, and attempting a task he cannot achieve."],
["Confucius","I am not bothered by the fact that I am unknown. I am bothered when I do not know others."],
["Epictetus","He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has."],
["Pablo Picasso","I am always doing that which I cannot do, in order that I may learn how to do it."],
["Barack Obama","If you're walking down the right path and you're willing to keep walking, eventually you'll make progress."],
["Ivy Baker Priest","The world is round and the place which may seem like the end may also be the beginning."],
["","Never miss an opportunity to make others happy, even if you have to leave them alone in order to do it."],
["Danielle Ingrum","Give it all you've got because you never know if there's going to be a next time."],
["Old German proverb","You have to take it as it happens, but you should try to make it happen the way you want to take it."],
["Ralph Blum","Nothing is predestined: The obstacles of your past can become the gateways that lead to new beginnings."],
["Bruce Lee","I'm not in this world to live up to your expectations and you're not in this world to live up to mine."],
["Thich Nhat Hanh","Sometimes your joy is the source of your smile, but sometimes your smile can be the source of your joy."],
["Walter Cronkite","I can't imagine a person becoming a success who doesn't give this game of life everything he's got."],
["Socrates","The greatest way to live with honor in this world is to be what we pretend to be."],
["Seneca","The conditions of conquest are always easy. We have but to toil awhile, endure awhile, believe always, and never turn back."],
["Chalmers","The grand essentials of happiness are: something to do, something to love, and something to hope for."],
["Thich Nhat Hanh","By living deeply in the present moment we can understand the past better and we can prepare for a better future."],
["Ralph Emerson","Do not be too timid and squeamish about your reactions. All life is an experiment. The more experiments you make the better."],
["Ralph Emerson","Do not go where the path may lead, go instead where there is no path and leave a trail."],
["Robert Louis Stevenson","There is no duty we so underrate as the duty of being happy. By being happy we sow anonymous benefits upon the world."],
["Napoleon Hill","Edison failed 10,000 times before he made the electric light. Do not be discouraged if you fail a few times."],
["","Yesterday is history. Tomorrow is a mystery. And today? Today is a gift that's why they call it the present."],
["Henry Thoreau","The only way to tell the truth is to speak with kindness. Only the words of a loving man can be heard."],
["Benjamin Disraeli","The greatest good you can do for another is not just to share your riches but to reveal to him his own."],
["Brian Tracy","You can only grow if you're willing to feel awkward and uncomfortable when you try something new."],
["Joan Didion","To free us from the expectations of others, to give us back to ourselves -- there lies the great, singular power of self-respect."],
["Mabel Newcomber","It is more important to know where you are going than to get there quickly. Do not mistake activity for achievement."],
["","When you don't know what you believe, everything becomes an argument. Everything is debatable. But when you stand for something, decisions are obvious."],
["Robert Graves","Intuition is the supra-logic that cuts out all the routine processes of thought and leaps straight from the problem to the answer."],
["Frank Wright","The thing always happens that you really believe in; and the belief in a thing makes it happen."],
["Francois de La Rochefoucauld","A true friend is the most precious of all possessions and the one we take the least thought about acquiring."],
["Epictetus","There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will."],
["Margaret Cousins","Appreciation can make a day -- even change a life. Your willingness to put it into words is all that is necessary."],
["","Every sixty seconds you spend angry, upset or mad, is a full minute of happiness you'll never get back."],
["Thomas Carlyle","This world, after all our science and sciences, is still a miracle; wonderful, inscrutable, magical and more, to whosoever will think of it."],
["Pearl Buck","Every great mistake has a halfway moment, a split second when it can be recalled and perhaps remedied."],
["Catherine Pulsifer","You can adopt the attitude there is nothing you can do, or you can see the challenge as your call to action."],
["Alfred Tennyson","The happiness of a man in this life does not consist in the absence but in the mastery of his passions."],
["Margaret Mead","Never doubt that a small group of thoughtful, committed people can change the world. Indeed. It is the only thing that ever has."],
["Ovid","Let your hook always be cast; in the pool where you least expect it, there will be a fish."],
["Remez Sasson","You get peace of mind not by thinking about it or imagining it, but by quietening and relaxing the restless mind."],
["Richard Bach","Your friends will know you better in the first minute you meet than your acquaintances will know you in a thousand years."],
["Pema Chodron","When you begin to touch your heart or let your heart be touched, you begin to discover that it's bottomless."],
["Richard Bach","If you love someone, set them free. If they come back they're yours; if they don't they never were."],
["David Jordan","Wisdom is knowing what to do next; Skill is knowing how to do it, and Virtue is doing it."],
["Richard Bach","Bad things are not the worst things that can happen to us. Nothing is the worst thing that can happen to us!"],
["Alan Watts","No valid plans for the future can be made by those who have no capacity for living now."],
["Oscar Wilde","The aim of life is self-development. To realize one's nature perfectly -- that is what each of us is here for."],
["Anatole France","To accomplish great things, we must not only act, but also dream; not only plan, but also believe."],
["Thomas Edison","The first requisite for success is the ability to apply your physical and mental energies to one problem incessantly without growing weary."],
["John Steinbeck","If we could learn to like ourselves, even a little, maybe our cruelties and angers might melt away."],
["","If we are facing in the right direction, all we have to do is keep on walking."],
["Eleanor Roosevelt","Remember always that you not only have the right to be an individual, you have an obligation to be one."],
["Denis Waitley","There are two primary choices in life: to accept conditions as they exist, or accept the responsibility for changing them."],
["Epictetus","If you seek truth you will not seek victory by dishonourable means, and if you find truth you will become invincible."],
["Eknath Easwaran","Through meditation and by giving full attention to one thing at a time, we can learn to direct attention where we choose."],
["Helen Keller","We could never learn to be brave and patient if there were only joy in the world."],
["Marcus Aurelius","If it is not right, do not do it; if it is not true, do not say it."],
["Norman Schwarzkopf","The truth of the matter is that you always know the right thing to do. The hard part is doing it."],
["Julie Morgenstern","Some people thrive on huge, dramatic change. Some people prefer the slow and steady route. Do what's right for you."],
["Blaise Pascal","Man is equally incapable of seeing the nothingness from which he emerges and the infinity in which he is engulfed."],
["Laura Teresa Marquez","Arrogance and rudeness are training wheels on the bicycle of life, for weak people who cannot keep their balance without them."],
["Chinese proverb","If you are patient in one moment of anger, you will escape one hundred days of sorrow."],
["Abraham Lincoln","When you have got an elephant by the hind legs and he is trying to run away, it's best to let him run."],
["Byron Pulsifer","Courage is not about taking risks unknowingly but putting your own being in front of challenges that others may not be able to."],
["Richard Bach","Can miles truly separate you from friends... If you want to be with someone you love, aren't you already there?"],
["Harry Kemp","The poor man is not he who is without a cent, but he who is without a dream."],
["Benjamin Disraeli","The greatest good you can do for another is not just share your riches, but reveal to them their own."],
["Buddha","Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment."],
["","Peace of mind is not the absence of conflict from life, but the ability to cope with it."],
["Helen Keller","Face your deficiencies and acknowledge them; but do not let them master you. Let them teach you patience, sweetness, insight."],
["John Kennedy","Change is the law of life. And those who look only to the past or present are certain to miss the future."],
["Marcus Aurelius","You have power over your mind -- not outside events. Realize this, and you will find strength."],
["Louis Pasteur","Let me tell you the secret that has led me to my goal: my strength lies solely in my tenacity."],
["Buddha","We are what we think. All that we are arises with our thoughts. With our thoughts, we make the world."],
["Henry Longfellow","He that respects himself is safe from others; he wears a coat of mail that none can pierce."],
["Wayne Dyer","I cannot always control what goes on outside. But I can always control what goes on inside."],
["Daisaku Ikeda","What matters is the value we've created in our lives, the people we've made happy and how much we've grown as people."],
["Epictetus","When you are offended at any man's fault, turn to yourself and study your own failings. Then you will forget your anger."],
["Rumi","Everyone has been made for some particular work, and the desire for that work has been put in every heart."],
["Napoleon Bonaparte","Take time to deliberate, but when the time for action has arrived, stop thinking and go in."],
["Dalai Lama","With realization of one's own potential and self-confidence in one's ability, one can build a better world."],
["Franklin Roosevelt","Happiness is not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort."],
["Pearl Buck","You cannot make yourself feel something you do not feel, but you can make yourself do right in spite of your feelings."],
["Mary Kay Ash","Those who are blessed with the most talent don't necessarily outperform everyone else. It's the people with follow-through who excel."],
["Albert Einstein","Try not to become a man of success, but rather try to become a man of value."],
["Sophocles","Men of perverse opinion do not know the excellence of what is in their hands, till some one dash it from them."],
["Rene Descartes","It is not enough to have a good mind; the main thing is to use it well."],
["Byron Pulsifer","Responsibility is not inherited, it is a choice that everyone needs to make at some point in their life."],
["Amelia Earhart","Never do things others can do and will do, if there are things others cannot do or will not do."],
["Jimmy Dean","I can't change the direction of the wind, but I can adjust my sails to always reach my destination."],
["George Allen","People of mediocre ability sometimes achieve outstanding success because they don't know when to quit. Most men succeed because they are determined to."],
["Joseph Roux","A fine quotation is a diamond on the finger of a man of wit, and a pebble in the hand of a fool."],
["Bernice Reagon","Life's challenges are not supposed to paralyse you, they're supposed to help you discover who you are."],
["Socrates","The greatest way to live with honour in this world is to be what we pretend to be."],
["Henri Bergson","To exist is to change, to change is to mature, to mature is to go on creating oneself endlessly."],
["Albert Einstein","Try not to become a man of success but rather try to become a man of value."],
["Byron Pulsifer","You can't create in a vacuum. Life gives you the material and dreams can propel new beginnings."],
["Buddha","Your work is to discover your world and then with all your heart give yourself to it."],
["Daisaku Ikeda","The person who lives life fully, glowing with life's energy, is the person who lives a successful life."],
["Richard Bach","Don't turn away from possible futures before you're certain you don't have anything to learn from them."],
["David Brinkley","A successful person is one who can lay a firm foundation with the bricks that others throw at him or her."],
["Buddha","All that we are is the result of what we have thought. The mind is everything. What we think we become."],
["Henri-Frederic Amiel","Work while you have the light. You are responsible for the talent that has been entrusted to you."],
];
